name: Plugin Subscribe GH Actions
on: [push]
jobs:
  Plugin-Subscribe-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Download Plugin
        uses: actions/checkout@v2

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
      - name: Install dependencies
        run: |
          composer install
          npm install


      - name: Run CS
        run: npm run cs
